name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate CN
      run: |
        mkdir cnout
        BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
        php update-manager/update-manager.php dscript "cnout/cn.txt" . cn
        php update-manager/update-manager.php script cnout/cn.txt "cnout/cn.file" 9999
    - name: Upload CN
      uses: actions/upload-artifact@v1
      with:
        name: cn
        path: cnout/
    - name: Generate EN
      run: |
        mkdir enout
        BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
        php update-manager/update-manager.php dscript "enout/en.txt" . en
        php update-manager/update-manager.php script enout/en.txt "enout/en.file" 9999
    - name: Upload EN
      uses: actions/upload-artifact@v1
      with:
        name: en
        path: enout/
    - name: Generate RU
      run: |
        mkdir ruout
        BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
        php update-manager/update-manager.php dscript "ruout/ru.txt" . ru
        php update-manager/update-manager.php script ruout/ru.txt "ruout/ru.file" 9999
    - name: Upload RU
      uses: actions/upload-artifact@v1
      with:
        name: ru
        path: ruout/

